# ====== BUILD STAGE ======
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /build

COPY pom.xml .
RUN mvn -B dependency:go-offline

COPY src ./src
RUN mvn -B package -DskipTests

# ====== RUNTIME STAGE ======
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /build/target/service-1-moderation-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
